export const plant: string = require('./shapes/plant_frag.glsl')
export const moss: string = require('./shapes/moss_frag.glsl')
export const spike: string = require('./shapes/spike_frag.glsl')
export const lightning: string = require('./shapes/lightning_frag.glsl')

export const stamp: string = require('./shapes/stamp_frag.glsl')
export const shatter: string = require('./shapes/shatter_frag.glsl')
export const cracks: string = require('./shapes/cracks_frag.glsl')

export const solid: string = require('./textures/solid_frag.glsl')
export const wreck: string = require('./textures/wreck_frag.glsl')
export const sandstone: string = require('./textures/sandstone_frag.glsl')
export const spiral: string = require('./textures/spiral_frag.glsl')
export const blocklines: string = require('./textures/blocklines_frag.glsl')
export const stripes: string = require('./textures/stripes_frag.glsl')
export const dunes: string = require('./textures/dunes_frag.glsl')
export const rust: string = require('./textures/rust_frag.glsl')
export const circuit: string = require('./textures/circuit_frag.glsl')
export const hatch: string = require('./textures/hatch_frag.glsl')
export const wires: string = require('./textures/wires_frag.glsl')
export const noise_directional: string = require('./textures/noise_directional_frag.glsl')

export const circle: string = require('./shapes/circle_frag.glsl')
export const glow: string = require('./shapes/glow_frag.glsl')
export const bulge: string = require('./shapes/bulge_frag.glsl')
export const ring: string = require('./shapes/ring_frag.glsl')
export const wave: string = require('./shapes/wave_frag.glsl')
export const sparkle: string = require('./shapes/sparkle_frag.glsl')
export const blink: string = require('./shapes/blink_frag.glsl')
export const rectangle: string = require('./shapes/rectangle_frag.glsl')
export const radial: string = require('./shapes/radial_frag.glsl')
export const rays: string = require('./shapes/rays_frag.glsl')
export const swirl: string = require('./shapes/swirl_frag.glsl')
export const streak: string = require('./shapes/streak_frag.glsl')
export const reticle: string = require('./shapes/reticle_frag.glsl')


export const orb: string = require('./effects/orb_frag.glsl')
export const beam: string = require('./effects/beam_frag.glsl')
export const acid: string = require('./effects/acid_frag.glsl')
export const mark: string = require('./effects/mark_frag.glsl')
export const pulse: string = require('./effects/pulse_frag.glsl')
export const spot: string = require('./effects/spot_frag.glsl')
export const shield: string = require('./effects/shield_frag.glsl')
export const grid: string = require('./effects/grid_frag.glsl')
export const battery: string = require('./effects/battery_frag.glsl')

export const batch2d_rg_frag: string = require('./batch2d_rg_frag.glsl')
export const debris_vert: string = require('./debris_vert.glsl')
export const sky_frag: string = require('./sky_frag.glsl')

export const mist_vert: string = require('./particle/mist_vert.glsl')
export const grass_vert: string = require('./particle/grass_vert.glsl')
export const smoke_frag: string = require('./particle/smoke_frag.glsl')
export const fire_frag: string = require('./particle/fire_frag.glsl')
export const foliage_frag: string = require('./particle/foliage_frag.glsl')